# Generated by Django 4.1.1 on 2022-10-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EspacioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasmaxreserva', models.SmallIntegerField()),
                ('aforo', models.SmallIntegerField()),
                ('habilitado', models.BooleanField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('hora', models.SmallIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('espacio_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.espacioreserva')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.estudiante')),
            ],
        ),
    ]
